# Generated by Django 5.1 on 2024-09-08 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='app',
            new_name='Player',
        ),
    ]
